### ISSUE TITLE
Install environment into base environment for Docker image

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/earth-analytics-binder#2]
Ideally, students shouldn't have to worry about choosing among environments within a Docker container. It would be best to be able to install the environment into the "base" or "root" conda environment, and have that be the only environment available within the container.

**Comment by lwasser** [comment]
hey @mbjoseph when i build the docker image - should it launch a notebook? i'm a bit confused as to what it did here:

<img width="326" alt="screen shot 2018-05-21 at 8 34 20 pm" src="https://user-images.githubusercontent.com/7649194/40339168-5f83dfb0-5d36-11e8-811d-83a8d299aaf3.png">

Also run this:

**Comment by mbjoseph** [comment]
Nope, building an image will only make it available to run. It won't actually run anything unless you fire up a container with docker run .... 

Building an image is like compiling a program!

**Comment by mbjoseph** [comment]
docker run -it -p 8888:8888 image-name

**Comment by mbjoseph** [comment]
Sorry on mobile

**Comment by lwasser** [comment]
No worries! i'm getting closer and updating the documentation as i go.
A few more questions

1. it does "run" but the url that it provides is 
   a. super weird with a ton of odd characters. is there a way to make it prettier like: localhost:8888
and 
  b. has two tokens that appear similar if not the same. 

`http://37fb53fe96ed:8888/?token=99dc977a6a8c3c8adda48f48932a3b846751ad32581bb630&token=99dc977a6a8c3c8adda48f48932a3b846751ad32581bb630` notice this url has two tokens too. i did try to remove one of them - it still doesnt work!

just curious if i'm doing something wrong!

**Comment by lwasser** [comment]
here are my running instruction updates

61da158f4a614a367324b4cd6c8e27ae9c21040f

**Comment by lwasser** [comment]
ooooh ooh ooh 'http://localhost:8888/` now it wants a token. why give u such a stupid long url tho?

**Comment by mbjoseph** [comment]
Not sure why it's putting some kind of hash in place of localhost in the URL. Also not sure why it gives two tokens. Weird..... Will check this out tomorrow!

**Comment by lwasser** [comment]
sure also @mbjoseph i was reading about jupyter authentication. it looks like we can control that potentially

https://jupyter-notebook.readthedocs.io/en/stable/public_server.html

is there any reason to authenticate on a local server? i know we want to use google oath for cloud implementation.

**Comment by mbjoseph** [comment]
No reason to authenticate if you're running locally as far as I know (assuming nobody is going to try to connect to your localhost). 

I'm going to close this issue, since we seem to be drifting and the Docker image now installs the deps into the root environment.
