### ISSUE TITLE
automagic rebuild of docker from YAML via travis

### ISSUE THREAD

**Issue by lwasser** [earthlab/earth-analytics-binder#7]
good morning @mbjoseph  i'm so much more productive now that i have turned OFF filtering of my github message in my email. 

Anyway does this repo have auto rebuild capacity or can it? it would be super duper cool to set that up to support additions to our conda environment? I'm working on a scope of work now and would like to identify what things we can "easily" build into our system vs things we need to contract out. it sounded like you may have a clever way already to attach travis to this so our dockerhub is updated as i update the environment. Can you kindly help me understand if this is possible?!

Thank you!! :)

**Comment by mbjoseph** [comment]
Hi @lwasser - yes! This is already set up. 

Every time the master branch changes (or a PR opens from another branch), Docker Hub will build a new image. You can see what's been built here: https://hub.docker.com/r/earthlab/earth-analytics/builds/

**Comment by lwasser** [comment]
you are a super awesome human @mbjoseph THANK YOU!! how the heck did you do that? Can you show me please? i had no idea this part could be done so quickly but i'm SO APPRECIATIVE that you did it.

**Comment by mbjoseph** [comment]
No problem @lwasser! I can show you this afternoon if you want.
